### ISSUE TITLE
route different on k8s node for same ipaddr

### ISSUE THREAD

**Issue by tsingloon** [projectcalico/node#1032]
## Expected Behavior
for same ipsddress, such as 172.16.192.192/26, ip routes on k8s nodes should be same, except blackhole route

## Current Behavior
for 172.16.192.192/26, k8s nodes (>30), have different routes:
    1) 172.16.192.192/26 via a.b.c.d dev tunl0  proto bird onlink
    2) 172.16.192.192/26 via a.b.c.e dev tunl0  proto bird onlink
node a.b.c.d and a.b.c.e all have blackhole route: blackhole 172.16.192.192/26  proto bird

## Possible Solution
ip route del or restart calico pod

## Context
pod ip such as 172.16.192.192, on some node could ping（include a.b.c.e, old node）, some node not（include a.b.c.d, new add）
172.16.192.192/26  ipamblock affinity: host is a.b.c.d

## Your Environment
* calico/node version: v3.7, k8s v1.13.4
* Operating System and version: centos 7u6, kernel 4.19 and 4.14
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@tsingloon Calico v3.7 is incredibly old at this point and no longer in support - it is very likely that this issue has been fixed since. Please could you try reproducing on a newer version of Calico?  If you can reproduce on a newer version of Calico I will re-open.
