### ISSUE TITLE
Node can't ping the pods on other node, when ipip ippool disabled.

### ISSUE THREAD

**Issue by maaoBit** [projectcalico/node#1057]
## Expected Behavior

When ipip ippool disabled, node can still ping the pods on other node.

## Current Behavior

When ipip ippool disabled, node can't ping the pods on other node. Because the address of tunl0 was removed by calico-node.

## Possible Solution

Disable ippool should not affect the connection of existing assigned addresses. How about modifying `determineEnabledPoolCIDRs` to `determinePoolCIDRs` which also return disabled ippool ?
https://github.com/projectcalico/node/blob/62c045519f8c4d23297eabb16bf00bf5301a6a42/pkg/allocateip/allocateip.go#L597

## Steps to Reproduce (for bugs)

1. Create a ipip pool
2. Create a pod , and assign address from the ipip pool
3. Set `disabled: true` for ipip pool 
4. Ping the pod ip from the other k8s node 

## Your Environment

* calico/node version: 3.18.4
* Operating System and version: CentOS7,K8s 1.18.5
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@maaoBit could you share a bit more information about your use case? What are you trying to achieve by setting the pool to disabled?

IPIP expects at least one enabled IP pool - `disabled: true` is signaling that the IP pool shouldn't be used, so I think it's doing the right thing by not using it.

**Comment by lmm** [comment]
Closing for now, please reopen if you're running into this issue again, thanks
