### ISSUE TITLE
Get-LastBootTime logic for windows seems fragile

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/node#1083]
Seems like in the calico node scripts we rely on WMI calls to create some kind of a semaphore for node timestamps.

https://github.com/projectcalico/node/blob/master/windows-packaging/CalicoWindows/node/node-service.ps1#L21

which eventually calls out to https://github.com/projectcalico/node/blob/master/windows-packaging/CalicoWindows/libs/calico/calico.psm1#L307 

```
function Get-LastBootTime()
{
    $bootTime = (Get-WmiObject win32_operatingsystem | select @{LABEL='LastBootUpTime';EXPRESSION={$_.lastbootuptime}}).LastBootUpTime
...
}
```

1) Should we instead be using `Get-CimInstance` ? 

2) What is the overall goal of the checking on the lastboottimes, and why do we compare this value with the values in the windows registry ? It want entirely obvious from reading the script ? 

i.e. WMI is going away, eventually https://blog.ipswitch.com/get-ciminstance-vs-get-wmiobject-whats-the-difference

**Comment by lmm** [comment]
> Should we instead be using Get-CimInstance ?

Thanks for reminding us. Yes, we should be updating this. I think we need it to work with newer Powershells.

> What is the overall goal of the checking on the lastboottimes

It's to reset networking if the node was just rebooted: https://github.com/projectcalico/node/blob/7c73e5697f206f817578ebed7131249e6d1cfac9/windows-packaging/CalicoWindows/node/node-service.ps1#L40-L42

**Comment by caseydavenport** [comment]
@lmm Now that https://github.com/projectcalico/node/pull/1156 is merged, what is left to do on this one?

**Comment by lmm** [comment]
Thanks for reporting the issue, @jayunit100 ! - I've fixed the WMI usage.
