### ISSUE TITLE
calico-node standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by mraghu4** [projectcalico/node#1137]
Is this issue [https://github.com/containerd/containerd/issues/5854](url) can be triaged from calico side?

**Comment by mraghu4** [comment]
this is the error message seen from containerd service 

containerd[2233]: time="2021-08-16T13:12:39.822323363+02:00" level=error msg="add cg to OOM monitor" error="open /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb2aa7c01_ed45_4985_af6e_0a57e2b126c1.slice/cri-containerd-06df8a6cdc54d546d4cc830361ac1452d2a7936b10e97bf75cedc2ef5745ec1d.scope/memory.oom_control: no such file or directory"

**Comment by caseydavenport** [comment]
Based on the conversation at the linked issue this doesn't seem like a Calico error, rather a problem with containerd downloading the images.
