### ISSUE TITLE
calico-node flooding/bombarding k8s API servers

### ISSUE THREAD

**Issue by gopiextrahop** [projectcalico/node#1200]
## Expected Behavior

calico-node should exponentially backoff if requests are timing out.

## Current Behavior

We are running calico-node v3.19.1. We use EKS (Kubernetes 1.18)with calico CNI. Our cluster has lots of worker nodes (700+). Recently we had an outage on AWS that caused one of the API servers in USW-AZ2 Availability Zone to go down. This caused all requests to go to the one remaining API server. The load was too much for the API server and it was taking a long time to respond. calico-node issues `LIST` pod request for `/api/v1/pods` for a full resync. Due to the load the API server takes more than a min to respond. But on the calico-node client side, the requests timeout in 60 sec. This caused calico-node to reissue the same request and this causes a vicious doom loop. Since there are 700+ nodes and due to API server being down, 200+ calico-nodes issue a full resync. We ended up having about 225 nodes issuing 6700 `LIST` pod request for `/api/v1/pods` for a full resync during a 30 min window.

```
{
    "kind": "Event",
    "apiVersion": "audit.k8s.io/v1",
    "level": "Request",
    "auditID": "adad7e00-b0fd-4d91-b957-de0a97adfc05",
    "stage": "ResponseComplete",
    "requestURI": "/api/v1/pods",
    "verb": "list",
    ...
}
```

## Possible Solution

* One possible solution is to exponential backoff when requests timeout giving the API server to catchup. 
* Or have a config that allows us to set how often to reissue requests on timeout.

## Steps to Reproduce (for bugs)

1. None. Just a production AWS AZ outage caused this.
2.
3.
4.

## Context

This causes our control plane to be unresponsive since API server was flooded with requests from calico-node.

## Your Environment

* calico/node version: 3.19.1
* Operating System and version: Amazon Linux running Kubernetes (EKS) 1.18
* Link to your project (optional):

**Comment by gopiextrahop** [comment]
We figured out that we were not using calico-typha due to a misconfiguration. We have fixed that issue. Hopefully this will become moot in that case.

**Comment by caseydavenport** [comment]
Yes, Typha is critical for a cluster of that scale. Let me know if that resolves your issue. 

Also related to this, we are working on a handful of optimizations in the way Calico does Lists and Watches against the Kubernetes API server which will help reduce load both with and without Typha.
