### ISSUE TITLE
changing https://docs.projectcalico.org/manifests/calico.yaml to put it into Append mode

### ISSUE THREAD

**Issue by vzuevsky** [projectcalico/node#1339]
Configuring k3s cluster with https://docs.projectcalico.org/manifests/calico.yaml

              chainInsertMode: Append
                description: 'ChainInsertMode controls whether Felix hooks the

## Expected Behavior

k3s calico-node runs in Append mode

## Current Behavior

kubectl apply -f calico.yaml
error: error parsing calico.yaml: error converting YAML to JSON: yaml: line 120: mapping values are not allowed in this context

## Possible Solution

None

## Steps to Reproduce (for bugs)

as above

## Context

https://docs.projectcalico.org/getting-started/kubernetes/k3s/multi-node-install

**Comment by caseydavenport** [comment]
@vzuevsky I don't understand - did you modify calico.yaml and you're getting that error? 

It looks to me like you're modifying the wrong part - that is the API definition, not a configuration option in the file. 

You need to edit the FelixConfiguration API to set that field, separately from calico.yaml: https://docs.projectcalico.org/reference/resources/felixconfig

**Comment by vzuevsky** [comment]
Hi Casey, thanks for quick reply. I have figured that out already. The key part missing from your answer is api version, took me a while to get it right, and the docs doesn't explain that either. But we are all good, please, feel free to close this chain.
