### ISSUE TITLE
Non-Calico CNI setups should not try to write kubeconfig

### ISSUE THREAD

**Issue by mattstam** [projectcalico/node#1370]
## Expected Behavior
No errors reported when Calico is chained on a different CNI (for example, Azure CNI). Should not attempt to write `calico-kubeconfig` since it is only necessary when Calico CNI is used.

## Current Behavior
The `calico-kubeconfig` is attempting to be written even when chained, which causes error:
```
[INFO][59] cni-config-monitor/token_watch.go 53: Notified of change to serviceaccount files. event="/var/run/secrets/kubernetes.io/serviceaccount/..2021_11_25_11_00_36.123474230": CREATE
[ERROR][59] cni-config-monitor/token_watch.go 99: Failed to write CNI plugin kubeconfig file error=open /host/etc/cni/net.d/calico-kubeconfig: no such file or directory
```

## Possible Solution
Do not run the token monitor in non-calico CNI setups, or at least avoid writing here: https://github.com/projectcalico/node/blame/master/pkg/cni/token_watch.go#L74

Maybe we can set `monitor-token` to false here: https://github.com/projectcalico/node/blob/master/cmd/calico-node/main.go#L58

## Steps to Reproduce (for bugs)
1. Create AKS cluster with Azure CNI + Calico chaining `az aks create -n ${CLUSTER_NAME}  -g ${RG} -l ${LOCATION} --network-plugin azure  --network-policy calico`
2. Do some update to the ServiceAccount to trigger the watch (what normally triggers this change?)
3. Might be intermittent issue, one attempt at repro did not see it but it might be something seen with different cluster versions due to changes in behavior on how. For example, for kubernetes versions `1.21.1`+ it seems to use projected volumes to pass this ServiceAccount token. So upgrade might be necessary.

## Context
Seeing hundreds of error logs from `calico-node` daemonset in cluster.

## Your Environment

* calico/node version: `v3.20.0`
* Operating System and version: Linux

**Comment by caseydavenport** [comment]
This sounds likely to be a bug with the Calico manifest that is packaged with AKS.

the `CALICO_MANAGE_CNI` environment variable is what controls whether or not the kubeconfig and token reconciliation loop is run or not. 

If Calico is not being used as the CNI plugin (as is the case using `--network-plugin azure`), then `CALICO_MANAGE_CNI=false` needs to be explicitly set. Here's the relevant bit of code: https://github.com/projectcalico/node/blob/master/filesystem/etc/rc.local#L73

**Comment by caseydavenport** [comment]
My colleagues just informed me that AKS now uses the Calico operator to install Calico, which should be setting this environment variable itself. Can you see if your calico/node daemonset has `CALICO_MANAGE_CNI=false` set? 

Could you also share the output of `kubectl get installations -o yaml`?

**Comment by mattstam** [comment]
`CALICO_MANAGE_CNI` is not set on these `--network-plugin azure` clusters. It is sounding like if this variable is not set, the default is not false? This may be some behavior to look at changing possibly.

**Comment by mattstam** [comment]
Here is output of `kubectl get installations -o yaml`:

```
apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: Installation
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"Installation","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"default"},"spec":{"calicoNetwork":{"bgp":"Disabled","ipPools":[],"nodeAddressAutodetectionV4":{"canReach":"1.1.1.1"}},"controlPlaneTolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"}],"imagePath":"oss/calico","imagePullSecrets":[],"kubernetesProvider":"AKS","registry":"mcr.microsoft.com/","typhaAffinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kubernetes.azure.com/mode","operator":"In","values":["system"]}]},"weight":100}]}}}}
    creationTimestamp: "2021-11-29T23:08:50Z"
    generation: 2
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: default
    resourceVersion: "1146"
    uid: d31c71b0-61ae-43c6-a475-41e9192384a8
  spec:
    calicoNetwork:
      bgp: Disabled
      ipPools: []
      linuxDataplane: Iptables
      nodeAddressAutodetectionV4:
        canReach: 1.1.1.1
    cni:
      ipam:
        type: AzureVNET
      type: AzureVNET
    controlPlaneTolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    flexVolumePath: /etc/kubernetes/volumeplugins/
    imagePath: oss/calico
    imagePullSecrets: []
    kubernetesProvider: AKS
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    registry: mcr.microsoft.com/
    typhaAffinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: In
              values:
              - system
          weight: 100
    variant: Calico
  status:
    computed:
      calicoNetwork:
        bgp: Disabled
        linuxDataplane: Iptables
        nodeAddressAutodetectionV4:
          canReach: 1.1.1.1
      cni:
        ipam:
          type: AzureVNET
        type: AzureVNET
      controlPlaneTolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      flexVolumePath: /etc/kubernetes/volumeplugins/
      imagePath: oss/calico
      kubernetesProvider: AKS
      nodeUpdateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      registry: mcr.microsoft.com/
      typhaAffinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                - system
            weight: 100
      variant: Calico
    mtu: 1500
    variant: Calico
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by mattstam** [comment]
Notably, we have set `kubernetesProvider: AKS`. Can operator use this information to set the env var `CALICO_MANAGE_CNI` to `false`? cc @tmjd

**Comment by tmjd** [comment]
I think it would be more appropriate to set that based on `spec.cni.type`.

**Comment by mattstam** [comment]
That should work as well!

**Comment by caseydavenport** [comment]
>  It is sounding like if this variable is not set, the default is not false? This may be some behavior to look at changing possibly.

The vast majority of users want this set to TRUE, which is the default, so I don't think we should change it.

> I think it would be more appropriate to set that based on spec.cni.type and if it is not Calico then to set CALICO_MANAGE_CNI to false.

This is the behavior in the latest master branch code, at least: https://github.com/tigera/operator/blob/master/pkg/render/node.go#L1155-L1160

What version of the operator do you have installed on the cluster?

**Comment by mattstam** [comment]
This was with operator v1.20.0, @caseydavenport your commit https://github.com/tigera/operator/commit/cb077951b1d301a8ef661121e0376691d7121218 wasn't in that version, right?

**Comment by mattstam** [comment]
Since it looks like this was fixed already in recent, will close this. One more question though @caseydavenport, can we manually set / override `CALICO_MANAGE_CNI` to mitigate, or will operator reconcile it back to an undefined value?

**Comment by tmjd** [comment]
Yeah the operator will reconcile any env vars added/modified/removed to any resources it deploys. It might not detect that they've been updated right away but it could reconcile them at any time and definitely will when it restarts.

**Comment by mattstam** [comment]
Thanks for the info, will close this since the required change has been merged.
