### ISSUE TITLE
Calico: Failed to turn off IPIP after setting the CALICO_IPV4POOL_IPIP to "off"

### ISSUE THREAD

**Issue by luotian-github** [projectcalico/node#15]
I am going to use calica without IPIP mode. After setting the CALICO_IPV4POOL_IPIP to "off" and restart the calico-node service, but the tunl0 is still there.

The following is my config:
```
[root@10 ~]# cat /lib/systemd/system/calico-node.service
[Unit]
Description=calico node
After=docker.service
Requires=docker.service

[Service]
User=root
PermissionsStartOnly=true
ExecStart=/usr/bin/docker run --net=host --privileged --name=calico-node \
  -e ETCD_ENDPOINTS=http://10.110.25.68:2379 \
  -e ETCD_CA_CERT_FILE= \
  -e ETCD_CERT_FILE= \
  -e ETCD_KEY_FILE= \
  -e NODENAME=${HOSTNAME} \
  -e IP= \
  -e NO_DEFAULT_POOLS= \
  -e AS= \
  -e CALICO_LIBNETWORK_ENABLED=true \
  -e IP6= \
  -e CALICO_NETWORKING_BACKEND=bird \
  -e FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT \
  -e FELIX_HEALTHENABLED=true \
  -e CALICO_IPV4POOL_CIDR=10.253.0.0/16 \
  -e CALICO_IPV4POOL_IPIP=off \
  -e IP_AUTODETECTION_METHOD=interface=ens3 \
  -e IP6_AUTODETECTION_METHOD=interface=ens3 \
  -v /etc/etcd/ssl:/etc/etcd/ssl \
  -v /var/run/calico:/var/run/calico \
  -v /lib/modules:/lib/modules \
  -v /run/docker/plugins:/run/docker/plugins \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/log/calico:/var/log/calico \
  quay.io/calico/node:v2.6.9
ExecStop=/usr/bin/docker rm -f calico-node
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```
And service status:
```
[root@10 ~]# systemctl status calico-node
● calico-node.service - calico node
   Loaded: loaded (/usr/lib/systemd/system/calico-node.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-06-07 02:29:19 EDT; 15min ago
  Process: 2001 ExecStop=/usr/bin/docker rm -f calico-node (code=exited, status=0/SUCCESS)
 Main PID: 2296 (docker)
   Memory: 4.8M
   CGroup: /system.slice/calico-node.service
           └─2296 /usr/bin/docker run --net=host --privileged --name=calico-node -e ETCD_EN...

Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.431 [INFO][7] startup.go ...s3
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.431 [INFO][7] startup.go ...ue
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.433 [INFO][7] etcd.go 111...et
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.434 [INFO][7] client.go 1...ID
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.473 [INFO][7] compat.go 7...sh
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.513 [INFO][7] startup.go ...96
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.702 [INFO][11] client.go ...nt
Jun 07 02:29:19 10.110.25.196 docker[2296]: 2018-06-07 06:29:19.713 [INFO][11] allocate_i...0"
Jun 07 02:29:22 10.110.25.196 docker[2296]: Starting libnetwork service
Jun 07 02:29:22 10.110.25.196 docker[2296]: Calico node started successfully
Hint: Some lines were ellipsized, use -l to show in full.
[root@10 ~]#

```
```
[root@10 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:1e:cb:fa brd ff:ff:ff:ff:ff:ff
    inet 10.110.25.196/24 brd 10.110.25.255 scope global dynamic ens3
       valid_lft 420sec preferred_lft 420sec
    inet6 fe80::5054:ff:fe1e:cbfa/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:2f:03:d3:5a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.253.159.0/32 scope global tunl0
       valid_lft forever preferred_lft forever
[root@10 ~]#
[root@10 ~]# ip route
default via 10.110.25.254 dev ens3  proto static  metric 100
10.110.25.0/24 dev ens3  proto kernel  scope link  src 10.110.25.196  metric 100
blackhole 10.253.159.0/26  proto bird
10.253.160.128/26 via 10.110.25.220 dev tunl0  proto bird onlink
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
[root@10 ~]#

```

How to disable the IPIP mode?

## Your Environment

* calico/node version: 2.6.9
* Operating System and version: redhat 7.2

**Comment by tmjd** [comment]
CALICO_IPV4POOL_IPIP is only used to set (or not set) IPIP when the default pool is first created.  So changing it and restarting calico-node is not expected to have any impact.  To update the IP Pool (and change IPIP) you can use the calicoctl command, see https://docs.projectcalico.org/v2.6/usage/configuration/ip-in-ip for some help with that.

**Comment by luotian-github** [comment]
@tmjd  I used calicoctl with a new ippool yaml, it looks working now. Thanks.
'''
[root@10 ~]# cat ippool.yaml
apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.253.0.0/16
spec:
  ipip:
    enabled: false
  nat-outgoing: true

'''

'''
[root@10 ~]# calicoctl apply -f ippool.yaml
Successfully applied 1 'ipPool' resource(s)
[root@10 ~]#
[root@10 ~]# calicoctl get ippool -o wide
CIDR                       NAT     IPIP
10.253.0.0/16              true    false
fd80:24e2:f998:72d6::/64   false   false

[root@10 ~]#

'''

'''
[root@10 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:e1:6c:16 brd ff:ff:ff:ff:ff:ff
    inet 10.110.25.220/24 brd 10.110.25.255 scope global dynamic ens3
       valid_lft 498sec preferred_lft 498sec
    inet6 fe80::5054:ff:fee1:6c16/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:d8:91:51:98 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d8ff:fe91:5198/64 scope link
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN
    link/ipip 0.0.0.0 brd 0.0.0.0
27: cali1a11eb6c1d6@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether b2:a2:82:c3:2d:0c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::b0a2:82ff:fec3:2d0c/64 scope link
       valid_lft forever preferred_lft forever
[root@10 ~]#
[root@10 ~]#
[root@10 ~]# ip route
default via 10.110.25.254 dev ens3  proto static  metric 100
10.110.25.0/24 dev ens3  proto kernel  scope link  src 10.110.25.220  metric 100
10.253.159.0/26 via 10.110.25.196 dev ens3  proto bird
blackhole 10.253.160.128/26  proto bird
10.253.160.139 dev cali1a11eb6c1d6  scope link
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
[root@10 ~]#

'''

**Comment by mdzddl** [comment]
@tmjd  i deploy calico in kubernets, when i change CALICO_IPV4POOL_IPIP to off, but it doesnt work,i cant use calicoctl to set ippool

**Comment by tmjd** [comment]
Why can't you use calicoctl to set the ippool?
If you are using kubernetes as the datastore then I'd suggest running calicoctl as a pod https://docs.projectcalico.org/v3.5/usage/calicoctl/install#installing-calicoctl-as-a-kubernetes-pod, it is the easiest way as you don't need any explicit configuration.
