### ISSUE TITLE
calico-node readiness probe fails on any single node being down.

### ISSUE THREAD

**Issue by ravilr** [projectcalico/node#153]
readiness probe here at calico-node daemonset pod: https://github.com/projectcalico/calico/blob/master/_includes/v3.5/manifests/calico-node.yaml#L279

seems to fail if any of the bgp peers connections are not in 'Established' state: https://github.com/projectcalico/node/blob/master/pkg/readiness/readiness.go#L74

Is there any impact on Calico functionality in a K8s cluster with readiness probe failing ? I mean, since there is no K8s Service resource that is fronting the calico-node daemonset pods, is this readiness check serving any purpose at all?

## Expected Behavior

would it make sense to fail the readiness check only if there are no global peers connected ? 
in case of 'node specific' peers,  not sure what should be the behavior

## Current Behavior

readiness probe fails on any bgp peer going down.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calico/node version:   calico/node:v3.5.1 
* Operating System and version: centos
* Link to your project (optional):

**Comment by fasaxc** [comment]
Calico should continue to function normally with a dead BGP peer (except for the fact that you'll be missing any routes from that peer).  The readiness check is required for rolling upgrade to work correctly.  It ensures that the BGP mesh is back up before the next calico/node in the cluster is upgraded.
