### ISSUE TITLE
why not check CIDR validation

### ISSUE THREAD

**Issue by daixiang0** [projectcalico/node#193]
As [code](https://github.com/projectcalico/node/blob/99a2eb05522e9a5b5ef567a9ceb5ae79ca85e03d/pkg/startup/startup.go#L717), for a CIDR(ip/mask), it only check ip not mask, so if i specify invalid CIDR like `192.167.0.0/12`, still can work. But in many case, pod network cannot communicate each other.

It just is found by my mistake, then i do some test, deploy with k8s, refer to [doc](https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/calico), calico version is 3.1:

| host network | CALICO_IPV4POOL_CIDR | result |
| --- | --- | --- |
| 192.168.50.xxx  | 192.167.0.0/12 | fail |
| 10.150.100.xxx  | 192.167.0.0/12 | success |
| 10.150.100.xxx  | 10.149.0.0/12 | fail |
| 192.168.50.xxx  | 10.149.0.0/12 | fail |

I know that default CALICO_IPV4POOL_CIDR is `192.168.0.0/16`, the above test may be an extreme example.

I do not test higher version, but after quick view related codes, this issue still exists.

**Comment by daixiang0** [comment]
| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |

**Comment by daixiang0** [comment]
For invalid CALICO_IPV4POOL_CIDR, If host network is in its range, the network does not work as expected, if not, network can work. It seems too ugly but exists. I do not know the reason, but add validation check can fix from origin.

**Comment by daixiang0** [comment]
@caseydavenport hi, any input?

**Comment by caseydavenport** [comment]
Yep, Calico shouldn't use an IP pool that overlaps with the host's network (or, any other network reachable from the Kubernetes cluster).

I don't know that there's much we can do about this - networks can conflict even if not present on that particular host. We could add validation, but it could be brittle (e.g, the network might exist on another host and we can't catch that).

Note that we do call this out in the Calico requirements on this page: https://docs.projectcalico.org/v3.6/getting-started/kubernetes/requirements

**Comment by daixiang0** [comment]
@caseydavenport hi, do you mean that check CIDR validation is meaningless, i can not agree with it.

**Comment by daixiang0** [comment]
@caseydavenport not saw related part in Network requirements(https://docs.projectcalico.org/v3.6/getting-started/kubernetes/requirements), do you mean add some comment here?

**Comment by caseydavenport** [comment]
I was referring to this section: 

> The IP range selected for pod IP addresses cannot overlap with any other IP ranges in your network, including:

> The Kubernetes service cluster IP range
>The range from which host IPs are allocated

**Comment by caseydavenport** [comment]
> do you mean that check CIDR validation is meaningless

Not that it is meaningless, just that it isn't really possible given the information Calico has - we don't know all of the addresses that exist in the network.

**Comment by daixiang0** [comment]
Hi, @caseydavenport 
> For invalid CALICO_IPV4POOL_CIDR, If host network is in its range, the network does not work as expected, if not, network can work. It seems too ugly but exists. 

Add a check when set pool cidr can skip invalid CIDR issue i think.

> The IP range selected for pod IP addresses cannot overlap with any other IP ranges in your network, including:

It is not linked to `POD_CIDR` in [docs](https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/calico), maybe add a link could be more helpful.

**Comment by daixiang0** [comment]
@caseydavenport any input?
