### ISSUE TITLE
Ignore the common excluded interfaces by default in auto-detect method INTERFACE-REGEX?

### ISSUE THREAD

**Issue by randmonkey** [projectcalico/node#210]
Is it possible to ignore the interfaces in `DEFAULT_INTERFACES_TO_EXCLUDE` in  auto-detect method `INTERFACE-REGEX`, unless some environment variable are set to specify another set of excluded interfaces ? Sometimes `IP_AUTODETECT_METHOD=interface=`(nothing ofter `interface=`) is specified  in spec of `calico-node` (may be the interface is not specified in some auto-deploy scripts). In this situation, `docker0` is usually used since it is usually in the first place of interfaces when sorted in alphabetical order. Excluding the default interfaces would fallback to `first-detect` method in this situation, reducing the probability of getting invalid IPs of node.

**Comment by caseydavenport** [comment]
If I understand correctly, do you mean to ignore any interfaces in DEFAULT_INTERFACES_TO_EXCLUDE when filtering interfaces based on a regex in this function? https://github.com/projectcalico/node/blob/5f91e603921c9c61538653068733df8195224888/pkg/startup/startup.go#L591-L601

Why not just set the interface regex to something that doesn't match `docker0`?

I'm not against it, but I don't think I fully understand the problem yet :)
