### ISSUE TITLE
IP_AUTODETECTION_METHOD always need change when default 'first-found'

### ISSUE THREAD

**Issue by zgfh** [projectcalico/node#255]
## Expected Behavior

When I install calico ,it will be problem ,because it will use interface of docker when `IP_AUTODETECTION_METHOD=first-found`, 
I have to change it to `interface=bondxx`,
but it is depend on env ,I have to change it every time when I install a new cluster

## Possible Solution

I have a idea, we change it use node ip of kubernetes found ,it ok?
```
NAME                      STATUS     ROLES    AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION              CONTAINER-RUNTIME
k8s-master1               Ready      master   146d   v1.12.3   10.33.32.61   <none>        Red Hat Enterprise Linux Server 7.2 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.6.1
```

**Comment by tmjd** [comment]
Would it work to use autodetection of `can-reach=8.8.8.8`, then maybe you wouldn't have to change it for new clusters?
Not all setups use kubernetes and even in some kubernetes deployments calico-node does not connect to the kubernetes API (like when using etcd as the datastore) so using the node ip is not always available. I'm not saying we couldn't add in code to read that but it isn't as simple as changing that over.
It would be nice if the Kubernetes downward API could provide the node IP and then that could be used in the manifest to set the `IP` environment variable but I don't think it is available.

**Comment by caseydavenport** [comment]
> status.hostIP - the node’s IP, available since v1.7.0-alpha.1

From here: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

Looks like maybe what you need does exist in the downward API?

**Comment by zgfh** [comment]
@caseydavenport should we change it to default ip? it will more easy to install without bug
```
    - name: IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
```

**Comment by caseydavenport** [comment]
I think changing it across all installations would be a breaking change for users relying on the current behavior. I'm not yet convinced that `status.hostIP` is always the desired value. 

If we should show that it is always the desired value then I think we could make that change.
