### ISSUE TITLE
TAGs/release

### ISSUE THREAD

**Issue by bartlomiejsawicki** [projectcalico/node#27]
Hi,
Is this code used to create quay.io/calico/node:v3.1.3 ?
If yes is it possible to create tag with every version with the same parameters used to create image?
At least some command with parameters which was used to create image could be placed in README. With just `make calico/node` I am missing some binaries like bird6 etc and I have to guess what should be in parameters to make.

**Comment by caseydavenport** [comment]
@bartlomiejsawicki calico/node v3.1.3 was actually built from the Calico repo on this branch: https://github.com/projectcalico/calico/tree/release-v3.1.

This repo is the new home for that code, and is where future releases will be built from starting at Calico v3.2.0. At that point, new tags will be created in this repository.
