### ISSUE TITLE
Calico-node failed to set NodeNetworkUnavailable

### ISSUE THREAD

**Issue by 420691301** [projectcalico/node#278]
## Expected Behavior
When we deployed the kubernetes cluster, sometimes we found that due to network problems (for example, kube-proxy has not updated iptables yet), calico-node could not set up NodeNetworkUnavailable, which would cause the pod could not be properly scheduled.  Calico-node simply prints an error without attempting to update condition or restart.

## What should happen
Node condition NodeNetworkUnavailable  is set successfully

## Current Behavior
Calico-node only try to update the node condition once. When failure, it outputs the error log and continues to run.

## Possible Solution
Maybe calico-node should retry or restart  if condition update failed

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calico/node version:
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
What version of calico are you running?
If you fixed the problem with kube-proxy does the issue resolve? Without kube-proxy Calico does not know how to reach the kubernetes apiserver (and cannot update the node condition).
It would be helpful if you could share some of the logs you saw if kube-proxy was fixed and the problem still persisted.

**Comment by 420691301** [comment]
I'm sorry for late. And thank you for your reply! 
I originally thought that calico needed to update NodeNetworkUnavailable in design. This is why I think the update process of NodeNetworkUnavailable is too simple.
And i found the [issue](https://github.com/projectcalico/canal/issues/74). Seem like I make a mistake...In fact, Cloud-controller-manager should address the issue.
