### ISSUE TITLE
Unspecific error with Debian 10 & Calico 3.8

### ISSUE THREAD

**Issue by loxal** [projectcalico/node#290]
After I let a Debian 10 node join a K8s cluster I get

`kube-system   pod/calico-node-h5qcv                          0/1     Running   0          2m53s`

The logs of the problematic pod show me: 

> 2019-08-12 14:20:01.250 [INFO][60] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=3.323203ms
> 2019-08-12 14:20:01.250 [INFO][60] int_dataplane.go 959: Finished applying updates to dataplane. msecToApply=3.8534129999999998
> 2019-08-12 14:20:11.786 [INFO][60] int_dataplane.go 945: Applying dataplane updates
> 2019-08-12 14:20:11.786 [INFO][60] ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
> 2019-08-12 14:20:11.786 [INFO][60] ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
> 2019-08-12 14:20:11.788 [INFO][60] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=1.582832ms
> 2019-08-12 14:20:11.788 [INFO][60] int_dataplane.go 959: Finished applying updates to dataplane. msecToApply=1.858974
> 2019-08-12 14:20:22.331 [INFO][60] int_dataplane.go 945: Applying dataplane updates
> 2019-08-12 14:20:22.332 [INFO][60] ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
> 2019-08-12 14:20:22.332 [INFO][60] ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
> 2019-08-12 14:20:22.335 [INFO][60] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=3.016457ms
> 2019-08-12 14:20:22.335 [INFO][60] int_dataplane.go 959: Finished applying updates to dataplane. msecToApply=3.6077510000000004
> 

The pod in question starts without any problems when a Debian 9 node joins the cluster.

**Comment by tmjd** [comment]
Could you include the output, from your debian 10 node, of `iptables version`?
You may need to switch the host to use the iptables 'legacy' backend, I'm guessing debian 10 is using the new nft backend.

**Comment by loxal** [comment]
> iptables v1.6.0

...and sorry, this was Debian 9.9 but the same issue occurred to me with Debian 10 which has 

> iptables v1.8.2 (nf_tables)

**Comment by loxal** [comment]
Actually it was vice versa, a Debian9 node could not join a Debian10 cluster.

**Comment by loxal** [comment]
I just reinitialized the cluster with Debian 9.9. `kubeadm reset` the joining Debian 9.9 node. Executed `iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X` on the joining Debian 9.9 node but still, I get:

> kubectl logs pod/calico-node-fdkxq -n kube-system
> 2019-08-12 16:23:52.600 [INFO][48] ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
> 2019-08-12 16:23:52.601 [INFO][48] ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
> 2019-08-12 16:23:52.603 [INFO][48] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=1.887963ms
> 2019-08-12 16:23:52.603 [INFO][48] int_dataplane.go 959: Finished applying updates to dataplane. msecToApply=2.315846
> 2019-08-12 16:24:03.081 [INFO][48] int_dataplane.go 945: Applying dataplane updates
> 2019-08-12 16:24:03.081 [INFO][48] ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
> 2019-08-12 16:24:03.081 [INFO][48] ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
> 2019-08-12 16:24:03.083 [INFO][48] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=2.363415ms
> 2019-08-12 16:24:03.084 [INFO][48] int_dataplane.go 959: Finished applying updates to dataplane. msecToApply=2.770878
> 2019-08-12 16:24:14.057 [INFO][48] int_dataplane.go 945: Applying dataplane updates
> 2019-08-12 16:24:14.057 [INFO][48] ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
> 2019-08-12 16:24:14.057 [INFO][48] ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
> 2019-08-12 16:24:14.059 [INFO][48] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=1.778425ms
> 2019-08-12 16:24:14.059 [INFO][48] int_dataplane.go 959: Finished applying updates to dataplane. msecToApply=2.048448
>

**Comment by tmjd** [comment]
The logs from calico-node that you are including look like everything is ok. Though it could be something else earlier in the logs.

For your deployment of calico did you set the Iptables Backend flag? If you set it for nft mode then I am not surprised that your 9.x host is not working correctly.

You should do a describe on the pod and see if the events suggest what the problem is.

Use the calicoctl command to check [BGP status](https://docs.projectcalico.org/v3.8/maintenance/troubleshooting#check-bgp-peer-status)

**Comment by Vashiru** [comment]
As @tmjd is suggesting, Debian 10 indeed defaults to the new iptables nft back-end. I ran into an issue with it the other day and got suggested to switch it to the legacy iptables. Things have been working fine since. See https://github.com/rancher/rancher/issues/22353#issuecomment-524059183 for instructions on how to switch it to the legacy back-end. 

Not sure if this will fix your issue, but it's worth a try.
