### ISSUE TITLE
Setting NetworkUnavailable to False can cause a delay in creating nodename file if kube-proxy is not up yet

### ISSUE THREAD

**Issue by cspargo** [projectcalico/node#307]
## Expected Behavior
When calico-node container starts, expect the /var/lib/calico/nodename file to be created immediately. 

## Current Behavior
calico-node performs the API call to set NetworkUnavailable to False, before setting the nodename file

## Possible Solution
perhaps set NetworkUnavailable to False after creating the nodename file?

## Steps to Reproduce (for bugs)
I think it's a race between when kube-proxy starts (which facilitates the connection to the api server on https://10.96.0.1:443/api...) and calico-node starts. We see it happen often. When kube-proxy is not running, calico node can't connect to 10.96.0.1 to make the API call to set NetworkUnavailable to False and takes 30 seconds to timeout.

## Context
This delay is a problem because install-cni has already completed and kubelet has already set the node to ready state. Subsequently pods start to get created on the node and experience this error

```
NetworkPlugin cni failed to set up pod "xyz" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
```
It seems to take 30 seconds for the API request to time out. After that, things start working properly. Here's the log of calico-node starting

```
Threshold time for bird readiness check:  30s
2019-08-28 22:44:08.610 [INFO][10] startup.go 264: Early log level set to info
2019-08-28 22:44:08.611 [INFO][10] startup.go 284: Using HOSTNAME environment (lowercase) for node name
2019-08-28 22:44:08.611 [INFO][10] startup.go 292: Determined node name: i-#############
2019-08-28 22:44:08.632 [INFO][10] startup.go 105: Skipping datastore connection test
2019-08-28 22:44:08.634 [INFO][10] startup.go 365: Building new node resource Name="i-#############"
2019-08-28 22:44:08.634 [INFO][10] startup.go 380: Initialize BGP data
2019-08-28 22:44:08.634 [INFO][10] startup.go 582: Using autodetected IPv4 address on interface eth0: ##.##.##.##/22
2019-08-28 22:44:08.634 [INFO][10] startup.go 450: Node IPv4 changed, will check for conflicts
2019-08-28 22:44:08.636 [INFO][10] startup.go 645: No AS number configured on node resource, using global value
2019-08-28 22:44:08.636 [INFO][10] startup.go 157: Setting NetworkUnavailable to False
2019-08-28 22:44:38.637 [ERROR][10] startup.go 160: Unable to set NetworkUnavailable to False error=Patch https://10.96.0.1:443/api/v1/nodes/i-#############/status: dial tcp 10.96.0.1:443: i/o timeout <-- 30 second delay
2019-08-28 22:44:38.642 [INFO][10] startup.go 528: FELIX_IPV6SUPPORT is false through environment variable
2019-08-28 22:44:38.647 [INFO][10] startup.go 189: Using node name: i-############# . <-- nodename set
```

## Your Environment
* calico/node version: 3.3.6
* Operating System and version: centos 7 on aws

**Comment by cspargo** [comment]
workaround i'm using is to add environment variables to both the calico-node and install-cni container spec, to tell it to use the external API server address instead of the internal service.
Added environment variables to both containers:

```
        - name: KUBERNETES_SERVICE_HOST
          value: "<your.apiserver.address>"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
```

**Comment by caseydavenport** [comment]
So, switching these around won't solve the problem IIUC.

The CNI plugin also needs kube-proxy to be running and functional in order to successfully network pods, so instead of seeing the above error you'll see an error indicating the CNI plugin can't access the apiserver.

Do you really want pods to start running before the kube-proxy is available anyway?

Maybe what we need is a shorter timeout on the connection, with retry logic, so that we don't wait a full 30 seconds before we move on.

**Comment by cspargo** [comment]
kube-proxy does normally become available very shortly after. However, even if it's running, calico-node still hangs on the initial request to the API for 30 seconds. Within this 30 second period, other pods can't start properly. 30 seconds matters to some people :-(

It's been a while since I looked at this last, but i noted at the time: "what happens is that the calico-init container first writes the config for the node into /etc/cni/net.d. When kubelet sees the config in that directory, it sets the node to Ready (at which point pods can/will be scheduled on the node). At the same time, calico-node also sees that config and starts setting up. It writes the /var/lib/calico/nodename file when it’s ready. TheAPI call to set NetworkUnavailable  to false, effectively adds a 30 second delay between when the node goes ready, and when the file /var/lib/calico/nodename is created, which results in the temporary issue with the pods starting. The reason for the 30 second delay appears to be because the kube-proxy pod had not yet started. It started several seconds after calico-node started. It appears that because kube-proxy had not yet set up the iptables rules to direct to the internal api service address on 10.96.0.1, the initial connection request hangs until it times out."

Yeah, a shorter connection timeout with retry might be the way to go.

**Comment by cspargo** [comment]
yes, that seems like a logical way to do things

**Comment by spikecurtis** [comment]
I've added a shorter connection timeout with retry to the call to set NetworkUnavailable to false. https://github.com/projectcalico/node/pull/387

We are also planning to gate installation of the CNI config until after we can access the apiserver.

**Comment by 3S-LoiNV** [comment]
Hello All
Do you know the cause of this error: 
"Unable to set Network Unavailable to False error=timed out patching node"
Thanks
