### ISSUE TITLE
Calico node version 3.1.3 source code

### ISSUE THREAD

**Issue by clyang82** [projectcalico/node#330]
I cannot find calico node version 3.1.3 source code. there is no version 3.1.3 branch or tag in `node`. Where can i find the source code for that version? Thanks.

**Comment by clyang82** [comment]
I just found that it seems the source code is in https://github.com/projectcalico/libcalico-go/tree/release-v3.1. what is the relationship between `node` and `libcalico-go`? Thanks

**Comment by caseydavenport** [comment]
Until v3.2 the node source was in the Calico repo: https://github.com/projectcalico/calico/tree/release-v3.1
