### ISSUE TITLE
bird mesh-mesh network is in wait state for long time  and node doesn't have routes programed by felix

### ISSUE THREAD

**Issue by rpenugonda** [projectcalico/node#355]
A node which used to be part of the kubernetes cluster goes to **NotReady** state and if the cluster autoscales and add new nodes, there is a delay in propagation of routes to the new node /s even after the calico-node pod is up and running. The new node cannot talk to old pods in the old nodes and vice-versa. Kubernetes schedules the pods since it thinks the new nodes are ready(as expected) and new pod ips are added to endpoints and iptables. This results in traffic drops. the issues fixes itself in 2-5 minutes.
## Expected Behavior
There should't be any delay in bgp routing info and or programming routes if a node is in that state or healthcheck which actually checks calico-node is ready (meaning bird is ready and felix created the routes)

bgp and routes should be programmed on the new nodes without delay.

this could be fixing the delay or the healthcheck
## Current Behavior
there is a delay in establishing bgp peers on the newly scaled nodes which results in felix not programming the routes and there by dropping incoming traffic to the service.

## Possible Solution
Making sure routes are programmed as fast as they can.
improving calico-node -bird-ready health check?.
an inmproved healthcheck where we see not just bird is ready but the mesh networking is up

## Steps to Reproduce (for bugs)

1. kubernetes cluster (v1.14.3)  with nodes and calico 3.7.x or 3.9.x with node-node mesh networking.
2. a simple ngnix deploy with external LB (ELB) and pods behind it. (may not be needed but easy to check) or atleast some pods so that you see routes across all other nodes
3. once all the nodes are ready and routes are in sync stop kubelet, this will put the node in NotReady state
4. autoscale the cluster via the deployment in step 2 or by other means (aws autoscaling)
5. hop on to the new node and check calicoctl node status or ip route and may be ping a pod ip which is living on old nodes.
6. you will see routes appear after 2-3 minutes and the ping successful

## Context

we loose traffic during deploys.

## Your Environment

* calico/node version: 3.7.2, 3.7.5 and 3.9.2 (tested in all these versions)
* Operating System and version:  4.14.138-114.102.amzn2.x86_64 (amzn2 linux)
* Link to your project (optional):

**Comment by tmjd** [comment]
In your step 5, what does the node status show? Does it show BGP peers are all established? Is node running? At that same time, what does a `kubectl get -n kube-system` show for the calico-node pods, are they all Ready? (except the pod from the disabled node)

Could you collect logs from the calico-node pod running on the newly scaled node?

**Comment by tmjd** [comment]
I meant the logs from the calico-node pod. You should be able to do that with `kubectl logs -n kube-system calico-node-xxxxxx`.

As a test, when you stop the kubelet also do a kubectl delete on the node that you've stopped?
My thought is that the nodes are trying to do a graceful restart with that downed node before attempting to establish a new connection and I'm wondering if you remove that downed one if they will stop trying to reconnect.

**Comment by rpenugonda** [comment]
when i delete the not ReadyNode it works the rules propogation gets and issue has less effect
![calico-wait-state](https://user-images.githubusercontent.com/9339957/68046197-4cd1c800-fca9-11e9-88b2-e4569bc813e9.png)
![calico-after-some-time](https://user-images.githubusercontent.com/9339957/68046205-50fde580-fca9-11e9-82c5-d572d1ec33a2.png)
[calico.log](https://github.com/projectcalico/node/files/3799099/ip-10-224-67-81_calico.log)

**Comment by tmjd** [comment]
The logs attached are they from when there was the big delay before pings worked or was it from when you deleted the K8s Node object for the node you disabled (stopped the kubelet)?

One thing you could try would to be to configure some route reflectors but you would want to make sure they are for nodes that are not going to be auto-scaled. Then you could disable the node-to-node BGP mesh. 
Here are the docs for setting up in-cluster route reflectors. https://docs.projectcalico.org/v3.10/networking/bgp#configuring-in-cluster-route-reflectors

**Comment by rpenugonda** [comment]
the logs attached contains all the info emitted by the pod starting from pings missing to when it recovered. i could try that, any worker nodes can auto scaled anytime. masters won't autoscale but only get replaced.
So the idea would here would be
1) create route reflectors on ex: master nodes(rr) (5 nodes)
2) all other workers will peer with route reflectors ex: master nodes so i would see each worker peering with 5rr's
3) the route reflectors peer among themselves.

have you seen any issues with rr's unavailable and route propagation times increase?

**Comment by tmjd** [comment]
We have not seen issues with either of those as far as I'm aware.
