### ISSUE TITLE
should we enable CALICO_MANAGE_CNI default?

### ISSUE THREAD

**Issue by zgfh** [projectcalico/node#391]
should we enable CALICO_MANAGE_CNI default to update kubeconfig ?

**Comment by tmjd** [comment]
Are you suggesting the default should be changed to enable? I think it is defaulted to disabled to prevent changing any behavior on upgrades.
If you're asking if you specifically should enable it, you'll have to make that decision based on what it does, `Tells Calico to update the kubeconfig file at /host/etc/cni/net.d/calico-kubeconfig on credentials change. [Default: false]` as found https://docs.projectcalico.org/v3.11/reference/node/configuration.
I hope the above helps.

**Comment by caseydavenport** [comment]
> I think it is defaulted to disabled to prevent changing any behavior on upgrades.

Yeah, we'll want to default enable this eventually, but for now it's only to support a beta feature of Kubernetes so it should be opt-in.

**Comment by ravilr** [comment]
@caseydavenport  Kubernetes v1.21 has BoundServiceAccountTokenVolume feature enabled by default, which means pod auto-mounted SA credential are rotated every hour, by default. It is time to enable CALICO_MANAGE_CNI: true and volumeMount: /host/etc/cni/net.d  in calico.node.yaml, by default ?

**Comment by ravilr** [comment]
On a Kubernetes v1.21 cluster, seeing stale token usage by calico-node(brought up by applying the default manifests at https://docs.projectcalico.org/manifests/calico-etcd.yaml, without `CALICO_MANAGE_CNI: true` set ) :

<img width="1149" alt="Screen Shot 2021-05-24 at 6 45 40 PM" src="https://user-images.githubusercontent.com/3928411/119428102-22978f00-bcc1-11eb-9f0f-d8676c23dff2.png">

**Comment by caseydavenport** [comment]
Yep we should definitely do this.
