### ISSUE TITLE
caller args error in function validateBlockSize(version int, blockSize int)   in github.com\projectcalico\node\pkg\startup\startup.go

### ISSUE THREAD

**Issue by liabio** [projectcalico/node#467]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calico/node version:
* Operating System and version:
* Link to your project (optional):

**Comment by liabio** [comment]
![image](https://user-images.githubusercontent.com/21979752/79686947-91ace380-8276-11ea-96b2-642d9a52c0aa.png)

**Comment by tmjd** [comment]
Thank you for reporting this. I've put up a PR to fix the code (#468).
