### ISSUE TITLE
Respect FELIX_HEALTHHOST in felixReadinessEp

### ISSUE THREAD

**Issue by gdziwoki** [projectcalico/node#486]
Health check and readiness check respect environment variable FELIX_HEALTHPORT but not FELIX_HEALTHHOST.
https://github.com/projectcalico/node/blob/28ef5a6a93a3330da2067cfdc406286946028e13/pkg/health/health.go#L48

## Expected Behavior
`/bin/calico-node -felix-health` should respect both env vars

## Current Behavior
If we change FELIX_HEALTHHOST to something different than localhost, the FELIX_HEALTHHOST:FELIX_HEALTHPORT/liveness endpoint will be available on that address, but `/bin/calico-node -felix-health` will fail

## Your Environment
* calico/node version: 3.13.3
* Operating System and version: Using helm chart

**Comment by tmjd** [comment]
Thank you for submitting this and the PR to fix it.
Could you share your use case for needing to set the HEALTHHOST for felix? I'm wondering if instead of adding this if we should just be removing from the documentation the ability to set the healthhost.

**Comment by gdziwoki** [comment]
We want to monitor calico-node using node-problem-detector, which means accessing it through nodes' IP address.
Right now, with default settings the built-in,local healthcheck will work, but the one performed by node-problem-detector will not.
If I change FELIX_HEALTHHOST, the external test will start working, but the built in healthcheck will fail.
