### ISSUE TITLE
Include calicoctl in docker image

### ISSUE THREAD

**Issue by valer-cara** [projectcalico/node#52]
I'm using calico w/ kubernetes as set up via kops. Each time I needed to debug a connectivity issue I had to manually pull `calicoctl` off github and check around.

## Expected Behavior

It'd be great if the image would contain `calicoctl`.

## Current Behavior

`find / -name calicoctl\*` returns no results

## Possible Solution

Add a step to the dockerfile (w/ the proper calicoctl version):
```
RUN wget -O /bin/calicoctl https://github.com/projectcalico/calicoctl/releases/download/v3.2.1/calicoctl-linux-amd64 && chmod +x /bin/calicoctl
```

## Your Environment

* calico/node version: 2.6.6 (though I looked in 3.2.1/latest and it's not there either)
* Operating System and version: linux 4.4.121-k8s // debian jessie

Thank you!

**Comment by caseydavenport** [comment]
@valer-cara I don't think it is desirable to include calicoctl within the node image. We're working to keep the image size small, and for the mainline case calicoctl shouldn't need to be installed on every node in the cluster.

Note that there is a `calico/ctl` image that makes installation easier - `docker pull calico/ctl`

It can then by copied to the host system using `docker cp`

It can even be run as a k8s pod: https://docs.projectcalico.org/v3.2/usage/calicoctl/install

**Comment by valer-cara** [comment]
Makes sense. I've actually ended up installing it on the node instead of the `calico-node` pods. That worked for me. Thanks for the info!
