### ISSUE TITLE
Bird bind socket error `Address in use`

### ISSUE THREAD

**Issue by zanetworker** [projectcalico/node#522]
We are occasionally seeing `Socket error: bind: Address in use` error log from `node`. 

Related to: https://github.com/projectcalico/node/issues/519 

## Expected Behavior
No error logs to be shown. 

## Context
kubectl logs calico-node-xxxx results in: 

```
bird: Mesh_10_250_10_60: Socket error: bind: Address in use
bird: Mesh_10_250_19_13: Socket error: bind: Address in use
bird: Mesh_10_250_21_169: Socket error: bind: Address in use
```

## Your Environment

* calico/node version: v3.13.4
* Operating System and version: CoreOS 2303.3.0
* Link to your project (optional): https://github.com/gardener/gardener-extension-networking-calico

**Comment by zanetworker** [comment]
cc @caseydavenport

**Comment by caseydavenport** [comment]
@zanetworker any idea what might be causing this? Are you seeing this at certain times (e.g., during a rolling update or another similar operation?)

The log suggests that Calico BGP is attempting to bind to port that is already in use, so something else on the host (another process or BGP instance, or maybe another instance of Calico?) is already using it.

**Comment by zanetworker** [comment]
it has been a while already, but when the issue happens I remember there was no other process trying to bind to that port on the host. Will try to spot another instance of the error to confirm again.

**Comment by fasaxc** [comment]
Do you use metallb or something like that?

**Comment by fasaxc** [comment]
Apart from the errors, is anything actually failing?  If BIRD is killed and restarts, it might take a few seconds for the socket from the old copy of BIRD to become ready for reuse.  If that's all it is then the message is likely benign.
