### ISSUE TITLE
[CVEs] docker image on clair, view high level CVEs

### ISSUE THREAD

**Issue by aesirteam** [projectcalico/node#523]
## Expected Behavior

![2020-06-19 10-44-24 的屏幕截图](https://user-images.githubusercontent.com/5821532/85091405-e7bbea00-b219-11ea-9d87-024093ad6ee8.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calico/node version:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
xref https://github.com/projectcalico/cni-plugin/issues/894

**Comment by caseydavenport** [comment]
These should be fixed in the latest Calico releases.
