### ISSUE TITLE
No libnetwork plugin on the calico image?

### ISSUE THREAD

**Issue by gcavalcante8808** [projectcalico/node#65]
Hi folks, I'm trying to use calico with docker standalone, but looks like there is not libnetwork-plugin in the image and calico cannot register itself as a docker plugin.

## Expected Behavior
When I run the command `docker network create --driver calico --ipam-driver calico-ipam net1`, the docker should use the calico network plugin (which is a legacy plugin, I know) to create a network.

## Current Behavior
Currently, the docker returns the message "No plugin named 'calico' found'.

## Possible Solution

Looking at calico-libnetwork logs in `/var/logs/calico/libnetwork/current` I saw the following message repeatedly:

./run: exec: line 3: libnetwork-plugin: not found

Then, I just executed the following commands in the container to fix it:

```
    docker exec -it calico-node apk add --no-cache curl ca-ceritificates
    docker exec -it calico-node curl -L --output /usr/bin/libnetwork-plugin https://github.com/projectcalico/libnetwork-plugin/releases/download/v1.1.3/libnetwork-plugin
    docker exec -it calico-node chmod +x /usr/bin/libnetwork-plugin
```
After that I just restarted the container and the command to create the network worked flawlessly.

## Steps to Reproduce (for bugs)

1. Execute calico installation that is detailed in https://docs.projectcalico.org/v2.0/getting-started/docker/installation/manual
2. Try to create a network following the guide: https://docs.projectcalico.org/v2.0/getting-started/docker/tutorials/simple-policy

## Context
I'm testing some 

## Your Environment

* Docker version: 17.06-ce
* calico/node version: 
Client Version:    v3.2.1
Build date:        2018-08-23T23:15:09+0000
Git commit:        3d1831a5
Cluster Version:   v3.2.1
Cluster Type:      unknown

* Operating System and version: Tried on Centos 7, Fedora 28, Debian 9.

**Comment by caseydavenport** [comment]
@gcavalcante8808 libnetwork support was removed in Calico v3.0.

There is a WIP PR to add it back here: https://github.com/projectcalico/libnetwork-plugin/pull/183

I don't expect that we'll add that back into the node image. The current plan is to continue libnetwork integration development through community support in the https://github.com/projectcalico/libnetwork-plugin repository.
