### ISSUE TITLE
iptables always uses legacy on arm64

### ISSUE THREAD

**Issue by kfox1111** [projectcalico/node#739]
The image is based on alpine 3.8. Iptables in that version only supports legacy, breaking on newer kernels.

## Expected Behavior
nft autodetection to work.

## Current Behavior
iptables is the only version available. not legacy or nft. So detection falls back to legacy always.

## Possible Solution
Upgrade to alpine 3.10+ as the base image. That version adds the iptables-legacy and iptables-nft binaries

## Steps to Reproduce (for bugs)
run a k8s cluster with arm64, a new enough kernel and calico. calico will put iptables rules in the wrong place.

* calico/node version: 3.17.0
* Operating System and version:
newest raspberian 64bit build.

**Comment by kfox1111** [comment]
I tested with upgrading to alpine 3.10. It works.

**Comment by caseydavenport** [comment]
@kfox1111 thanks for digging into this, how would you feel about submitting a PR with your working changes?

**Comment by kfox1111** [comment]
I tried once. https://github.com/projectcalico/node/pull/740 The cla's a problem. its just a single version number change so it really shouldn't need a cla over. Anyone should be able to create the patch in a couple of minutes though.

Thanks,
Kevin

**Comment by caseydavenport** [comment]
@kfox1111 ahh, gotcha. In that case, I've got a PR for you here: https://github.com/projectcalico/node/pull/755
