### ISSUE TITLE
Request: provide startup.go as a standalone binary

### ISSUE THREAD

**Issue by Youkoulayley** [projectcalico/node#8]
Hi, 

We are currently installing calico in service mode and without the startup script, Calico doesn't work. Actually, we fetch this project and build by hand the startup script, but this is not a viable functioning.

So, is moving the startup script in another project feasible?

Thanks in advance.

**Comment by caseydavenport** [comment]
@Youkoulayley mind if I ask why you need to run without the startup script? 

I don't think splitting the startup code into a separate repository is feasible at this time - I'd recommend running the released `calico/node` image.

**Comment by Youkoulayley** [comment]
@caseydavenport I use each components of calico as systemd service, I am not using the calico/node image.

So when I start all the services the ETCD database is not initialized. The startup script is present only on the calico/node repo, and I have to clone this repo to build the startup script and I just wanted to know if it was possible to isolate this script in an another repo and provide the binary as you do for others components.

**Comment by caseydavenport** [comment]
>  I use each components of calico as systemd service, I am not using the calico/node image.

Yep, I was just curious as to why you want to do that rather than run calico/node.

While I still would recommend just running calico/node, what about something like this to get the released binary?

```
docker pull calico/node
docker create -name calico-node calico/node
docker cp calico-node:/filesystem/bin/startup <host dir>
docker rm -f calico-node
```

**Comment by Youkoulayley** [comment]
Thanks I will do that instead :)
